### ISSUE TITLE
Style tiles

### ISSUE THREAD

**Issue by dmerrill88** [rpainterj/tiy_assignments#3]
All your tiles look like you nailed them very well. Your colors and designs go very well with each other on each tile. Maybe play with your body font on tile 3. Your movement seem like is has a very military kind of feel, so maybe find some cool bold fonts.

**Comment by rpainterj** [comment]
Thanks for the feedback!

**Comment by dmerrill88** [comment]
Sure thing. Hope all is going well on the job hunt.
